/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ajtokjatek;

/**
 *
 * @author RichterBalázsKriszti
 */
public class AjtokJatek extends javax.swing.JFrame {

    /**
     * Creates new form AjtokJatek
     */
    public AjtokJatek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBTNElsoGomb = new javax.swing.JButton();
        JBTNMasodikGomb = new javax.swing.JButton();
        JBTNHarmadikGomb = new javax.swing.JButton();
        JLBKerdes = new javax.swing.JLabel();
        PNLStatisztika = new javax.swing.JPanel();
        PNLKorSzam = new javax.swing.JPanel();
        txtfldKorSzam = new javax.swing.JTextField();
        PNLNyeresArany = new javax.swing.JPanel();
        jlbCsereNelkul = new javax.swing.JLabel();
        JLBCserevel = new javax.swing.JLabel();
        jtxtfldCsereNelkulSzamlalo = new javax.swing.JTextField();
        jtxtfldCsereSzamlalo = new javax.swing.JTextField();
        PNLJatekvezerlo = new javax.swing.JPanel();
        JBTNUjJatek = new javax.swing.JButton();
        JBTNValasztasCsere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBTNElsoGomb.setBackground(new java.awt.Color(153, 153, 153));
        JBTNElsoGomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajtokjatek/ajto-removebg-preview.png"))); // NOI18N

        JBTNMasodikGomb.setBackground(new java.awt.Color(153, 153, 153));
        JBTNMasodikGomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajtokjatek/ajto-removebg-preview.png"))); // NOI18N

        JBTNHarmadikGomb.setBackground(new java.awt.Color(153, 153, 153));
        JBTNHarmadikGomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajtokjatek/ajto-removebg-preview.png"))); // NOI18N

        JLBKerdes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLBKerdes.setText("Melyik ajtót választod? Kattints az ajtóra!");
        JLBKerdes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PNLStatisztika.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Statisztika", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        PNLKorSzam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lejátszott körök száma", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtfldKorSzam.setEditable(false);
        txtfldKorSzam.setText("*KÖR SZÁM HELY*");

        javax.swing.GroupLayout PNLKorSzamLayout = new javax.swing.GroupLayout(PNLKorSzam);
        PNLKorSzam.setLayout(PNLKorSzamLayout);
        PNLKorSzamLayout.setHorizontalGroup(
            PNLKorSzamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLKorSzamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtfldKorSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        PNLKorSzamLayout.setVerticalGroup(
            PNLKorSzamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLKorSzamLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtfldKorSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PNLNyeresArany.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nyerési arány", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jlbCsereNelkul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbCsereNelkul.setText("Cserélés nélkül:");

        JLBCserevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLBCserevel.setText("Cserélés módszerrel:");

        jtxtfldCsereNelkulSzamlalo.setEditable(false);
        jtxtfldCsereNelkulSzamlalo.setText("*SZÁMLÁLÓ*");

        jtxtfldCsereSzamlalo.setEditable(false);
        jtxtfldCsereSzamlalo.setText("*SZÁMLÁLÓ*");

        javax.swing.GroupLayout PNLNyeresAranyLayout = new javax.swing.GroupLayout(PNLNyeresArany);
        PNLNyeresArany.setLayout(PNLNyeresAranyLayout);
        PNLNyeresAranyLayout.setHorizontalGroup(
            PNLNyeresAranyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLNyeresAranyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PNLNyeresAranyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLBCserevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbCsereNelkul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNLNyeresAranyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtfldCsereNelkulSzamlalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfldCsereSzamlalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        PNLNyeresAranyLayout.setVerticalGroup(
            PNLNyeresAranyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLNyeresAranyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLNyeresAranyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBCserevel)
                    .addComponent(jtxtfldCsereNelkulSzamlalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNLNyeresAranyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCsereNelkul)
                    .addComponent(jtxtfldCsereSzamlalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PNLStatisztikaLayout = new javax.swing.GroupLayout(PNLStatisztika);
        PNLStatisztika.setLayout(PNLStatisztikaLayout);
        PNLStatisztikaLayout.setHorizontalGroup(
            PNLStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLStatisztikaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNLKorSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNLNyeresArany, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNLStatisztikaLayout.setVerticalGroup(
            PNLStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLStatisztikaLayout.createSequentialGroup()
                .addGroup(PNLStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNLNyeresArany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNLKorSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PNLJatekvezerlo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Játékvezérlő", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        JBTNUjJatek.setText("Új játék kezdése");

        JBTNValasztasCsere.setText("Választás csere");

        javax.swing.GroupLayout PNLJatekvezerloLayout = new javax.swing.GroupLayout(PNLJatekvezerlo);
        PNLJatekvezerlo.setLayout(PNLJatekvezerloLayout);
        PNLJatekvezerloLayout.setHorizontalGroup(
            PNLJatekvezerloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLJatekvezerloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLJatekvezerloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBTNUjJatek)
                    .addComponent(JBTNValasztasCsere))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNLJatekvezerloLayout.setVerticalGroup(
            PNLJatekvezerloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLJatekvezerloLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JBTNUjJatek)
                .addGap(18, 18, 18)
                .addComponent(JBTNValasztasCsere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLBKerdes)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBTNElsoGomb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTNMasodikGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PNLStatisztika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBTNHarmadikGomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PNLJatekvezerlo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLBKerdes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JBTNElsoGomb)
                        .addComponent(JBTNHarmadikGomb))
                    .addComponent(JBTNMasodikGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PNLJatekvezerlo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PNLStatisztika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjtokJatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjtokJatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjtokJatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjtokJatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjtokJatek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNElsoGomb;
    private javax.swing.JButton JBTNHarmadikGomb;
    private javax.swing.JButton JBTNMasodikGomb;
    private javax.swing.JButton JBTNUjJatek;
    private javax.swing.JButton JBTNValasztasCsere;
    private javax.swing.JLabel JLBCserevel;
    private javax.swing.JLabel JLBKerdes;
    private javax.swing.JPanel PNLJatekvezerlo;
    private javax.swing.JPanel PNLKorSzam;
    private javax.swing.JPanel PNLNyeresArany;
    private javax.swing.JPanel PNLStatisztika;
    private javax.swing.JLabel jlbCsereNelkul;
    private javax.swing.JTextField jtxtfldCsereNelkulSzamlalo;
    private javax.swing.JTextField jtxtfldCsereSzamlalo;
    private javax.swing.JTextField txtfldKorSzam;
    // End of variables declaration//GEN-END:variables
}
